/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_SE;

import java.applet.Applet;
import java.applet.AudioClip;
import java.io.File;
import java.net.URL;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import sun.audio.*;

/**
 *
 * @author mserfaty
 */
public class FAccueil extends javax.swing.JFrame {

    private FJeu ficheJeu;
    private FRegles ficheRegles;
    private FScores ficheScores;
    
    public FAccueil() {

        initComponents();
        ficheJeu = new FJeu(this,false); 
        ficheRegles = new FRegles(this,false);
        ficheScores = new FScores(this,false);
        play();
    }
    
   public void play() {
  try {
   File file = new File("cello.wav");
   Clip clip = AudioSystem.getClip();
   clip.open(AudioSystem.getAudioInputStream(file));
   clip.start();
  } catch (Exception e) {
   System.err.println("Erreur musique");
  }
 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFond = new javax.swing.JPanel();
        pNoms = new javax.swing.JPanel();
        lNoms = new javax.swing.JLabel();
        lNoms1 = new javax.swing.JLabel();
        lGroupe = new javax.swing.JLabel();
        lDate = new javax.swing.JLabel();
        lTitre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bJouer = new javax.swing.JButton();
        bQuitter = new javax.swing.JButton();
        bRegles = new javax.swing.JButton();
        bScores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIDE EFFECT");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setForeground(java.awt.Color.darkGray);

        pFond.setBackground(new java.awt.Color(51, 51, 51));
        pFond.setForeground(new java.awt.Color(51, 51, 51));

        pNoms.setBackground(new java.awt.Color(51, 51, 51));
        pNoms.setForeground(new java.awt.Color(255, 102, 102));

        lNoms.setForeground(new java.awt.Color(153, 153, 153));
        lNoms.setText("de la CROIX Sulwen");

        lNoms1.setForeground(new java.awt.Color(153, 153, 153));
        lNoms1.setText("SERFATY Matthieu");

        lGroupe.setForeground(new java.awt.Color(153, 153, 153));
        lGroupe.setText("Groupe D");

        lDate.setForeground(new java.awt.Color(153, 153, 153));
        lDate.setText("17/03/2017");

        javax.swing.GroupLayout pNomsLayout = new javax.swing.GroupLayout(pNoms);
        pNoms.setLayout(pNomsLayout);
        pNomsLayout.setHorizontalGroup(
            pNomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNomsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pNomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNoms)
                    .addComponent(lNoms1)
                    .addComponent(lGroupe)
                    .addComponent(lDate))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pNomsLayout.setVerticalGroup(
            pNomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNomsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lNoms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNoms1)
                .addGap(18, 18, 18)
                .addComponent(lGroupe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lDate)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lTitre.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 36)); // NOI18N
        lTitre.setForeground(new java.awt.Color(153, 153, 153));
        lTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitre.setText("SIDE EFFECT");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        bJouer.setBackground(new java.awt.Color(51, 51, 255));
        bJouer.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        bJouer.setForeground(new java.awt.Color(204, 204, 204));
        bJouer.setText("JOUER");
        bJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJouerActionPerformed(evt);
            }
        });

        bQuitter.setBackground(new java.awt.Color(153, 0, 51));
        bQuitter.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        bQuitter.setForeground(new java.awt.Color(204, 204, 204));
        bQuitter.setText("QUITTER");
        bQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitterActionPerformed(evt);
            }
        });

        bRegles.setBackground(new java.awt.Color(51, 51, 255));
        bRegles.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        bRegles.setForeground(new java.awt.Color(204, 204, 204));
        bRegles.setText("Règles ");
        bRegles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReglesActionPerformed(evt);
            }
        });

        bScores.setBackground(new java.awt.Color(51, 51, 255));
        bScores.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        bScores.setForeground(new java.awt.Color(204, 204, 204));
        bScores.setText("High Scores");
        bScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bScoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bRegles, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bJouer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(bScores, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bJouer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bScores, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(bRegles, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout pFondLayout = new javax.swing.GroupLayout(pFond);
        pFond.setLayout(pFondLayout);
        pFondLayout.setHorizontalGroup(
            pFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pNoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(pFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        pFondLayout.setVerticalGroup(
            pFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pNoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pFondLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pFond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pFond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJouerActionPerformed
        this.setVisible(false);
        ficheJeu.setVisible(true);
        
    }//GEN-LAST:event_bJouerActionPerformed

    private void bQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bQuitterActionPerformed

    private void bReglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReglesActionPerformed
        this.setVisible(false);
        ficheRegles.setVisible(true);
    }//GEN-LAST:event_bReglesActionPerformed

    private void bScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bScoresActionPerformed
        this.setVisible(false);
        ficheScores.setVisible(true);
        
    }//GEN-LAST:event_bScoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bJouer;
    private javax.swing.JButton bQuitter;
    private javax.swing.JButton bRegles;
    private javax.swing.JButton bScores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lGroupe;
    private javax.swing.JLabel lNoms;
    private javax.swing.JLabel lNoms1;
    private javax.swing.JLabel lTitre;
    private javax.swing.JPanel pFond;
    private javax.swing.JPanel pNoms;
    // End of variables declaration//GEN-END:variables
}
