/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_SE;

/**
 *
 * @author mserfaty
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pP1 = new javax.swing.JPanel();
        pP2 = new javax.swing.JPanel();
        pP3 = new javax.swing.JPanel();
        pP4 = new javax.swing.JPanel();
        pGrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 582));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pP1.setBackground(new java.awt.Color(255, 51, 51));
        pP1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pP1MouseDragged(evt);
            }
        });
        pP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pP1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pP1Layout = new javax.swing.GroupLayout(pP1);
        pP1.setLayout(pP1Layout);
        pP1Layout.setHorizontalGroup(
            pP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pP1Layout.setVerticalGroup(
            pP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pP1);

        pP2.setBackground(new java.awt.Color(255, 51, 51));
        pP2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pP2MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout pP2Layout = new javax.swing.GroupLayout(pP2);
        pP2.setLayout(pP2Layout);
        pP2Layout.setHorizontalGroup(
            pP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pP2Layout.setVerticalGroup(
            pP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pP2);

        pP3.setBackground(new java.awt.Color(255, 51, 51));
        pP3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pP3MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout pP3Layout = new javax.swing.GroupLayout(pP3);
        pP3.setLayout(pP3Layout);
        pP3Layout.setHorizontalGroup(
            pP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pP3Layout.setVerticalGroup(
            pP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pP3);

        pP4.setBackground(new java.awt.Color(255, 51, 51));
        pP4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pP4MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout pP4Layout = new javax.swing.GroupLayout(pP4);
        pP4.setLayout(pP4Layout);
        pP4Layout.setHorizontalGroup(
            pP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pP4Layout.setVerticalGroup(
            pP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pP4);

        pGrille.setBackground(new java.awt.Color(255, 51, 204));
        pGrille.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pGrilleMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout pGrilleLayout = new javax.swing.GroupLayout(pGrille);
        pGrille.setLayout(pGrilleLayout);
        pGrilleLayout.setHorizontalGroup(
            pGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        pGrilleLayout.setVerticalGroup(
            pGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        getContentPane().add(pGrille);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pP1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pP1MouseDragged
        int x = evt.getX();//coord de la souris par rapport au panel
        int y = evt.getY();
        int nouvX = x+pP1.getX();
        int nouvY = y+pP1.getY();
        pP1.setLocation(nouvX,nouvY);
    }//GEN-LAST:event_pP1MouseDragged

    private void pGrilleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGrilleMouseDragged
         int x = evt.getX();//coord de la souris par rapport au panel
        int y = evt.getY();
        int nouvX = x+pGrille.getX();
        int nouvY = y+pGrille.getY();
        pGrille.setLocation(nouvX,nouvY);
    }//GEN-LAST:event_pGrilleMouseDragged

    private void pP2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pP2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pP2MouseDragged

    private void pP3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pP3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pP3MouseDragged

    private void pP4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pP4MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pP4MouseDragged

    private void pP1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pP1MouseReleased
       this.pack();
    }//GEN-LAST:event_pP1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pGrille;
    private javax.swing.JPanel pP1;
    private javax.swing.JPanel pP2;
    private javax.swing.JPanel pP3;
    private javax.swing.JPanel pP4;
    // End of variables declaration//GEN-END:variables
}
